# docker-compose development override for femr service
---
version: "3.7"
services:
  femr:
    command: sh -c "cd /opt/app && flask run --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      FLASK_ENV: development
      # use static frontend built in docker image
      STATIC_DIR: /opt/cosri-patientsearch/patientsearch/static/
    volumes:
    # set in .env
      - "${FEMR_CHECKOUT_DIR}/:/opt/app"
